services:
  app_blue:
    image: "${BLUE_IMAGE}"
    container_name: app_blue
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - X_APP_POOL=blue
    ports:
      - "${BLUE_HOST_PORT}:${PORT}"
    restart: unless-stopped

  app_green:
    image: "${GREEN_IMAGE}"
    container_name: app_green
    environment:
      - PORT=${PORT}
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - X_APP_POOL=green
    ports:
      - "${GREEN_HOST_PORT}:${PORT}"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - app_blue
      - app_green
    ports:
      - "${NGINX_PORT}:8080"
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - BLUE_SERVICE_HOST=app_blue
      - GREEN_SERVICE_HOST=app_green
      - APP_PORT=${PORT}
    volumes:
      - ./nginx/docker-entrypoint.sh:/docker-entrypoint.sh:ro
      - nginx_logs:/var/log/nginx  # ✅ Shared log volume
    entrypoint: ["/docker-entrypoint.sh"]

  alert_watcher:
    build: ./watcher
    container_name: alert_watcher
    env_file:
      - .env
    volumes:
      - nginx_logs:/var/log/nginx  # ✅ Same shared volume
    depends_on:
      - nginx

volumes:
  nginx_logs: